/* References public/brand-icons.svg, generated by scripts/build-icon-sprite.mjs.
   The sprite is one cacheable request instead of ~80 KB of path data repeated
   in the HTML and again in the RSC payload. `fill` is inherited, so the icon
   still takes its colour from the chip. */
export function BrandIcon({ slug }: { slug?: string }) {
  if (!slug) {
    return null;
  }
  return (
    <svg aria-hidden className="chip-icon">
      <use href={`/brand-icons.svg#${slug}`} />
    </svg>
  );
}
